---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: 'NetApp SnapMirror replica i dati ad alta velocità su LAN o WAN, garantendo un"elevata disponibilità dei dati e una rapida replicazione degli stessi sia in ambienti virtuali che tradizionali.  Quando si replicano i dati sui sistemi di storage NetApp e si aggiornano continuamente i dati secondari, i dati vengono mantenuti aggiornati e restano disponibili ogni volta che ne hai bisogno. Non sono richiesti server di replicazione esterni.' 
---
= Scopri di più su NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror replica i dati ad alta velocità su LAN o WAN, garantendo un'elevata disponibilità dei dati e una rapida replicazione degli stessi sia in ambienti virtuali che tradizionali.  Quando si replicano i dati sui sistemi di storage NetApp utilizzando NetApp Replication e si aggiornano continuamente i dati secondari, i dati vengono mantenuti aggiornati e restano disponibili ogni volta che ne hai bisogno. Non sono richiesti server di replicazione esterni.



[[netapp-console]]
== NetApp Console

È possibile accedere a NetApp Replication tramite la NetApp Console.

La Console offre una gestione centralizzata dei servizi di storage e dati NetApp in ambienti on-premises e cloud a livello enterprise. La Console è necessaria per accedere e utilizzare i servizi dati NetApp. Come interfaccia di gestione, ti permette di gestire molte risorse di storage da un'unica interfaccia. Gli amministratori della Console possono controllare l'accesso allo storage e ai servizi per tutti i sistemi all'interno dell'azienda.

Non hai bisogno di una licenza o di un abbonamento per iniziare a usare la Console. Sostieni dei costi solo quando devi distribuire agenti della Console nel tuo cloud per garantire la connettività ai tuoi sistemi storage o ai servizi dati di NetApp. Tuttavia, alcuni servizi dati di NetApp accessibili dalla Console richiedono una licenza o un abbonamento.

Scopri di più su  https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"].



[[features]]
== Caratteristiche

* Replicare i dati tra i sistemi di archiviazione ONTAP per supportare il backup e il ripristino di emergenza sul cloud o tra cloud.
* Garantisci l'affidabilità del tuo ambiente DR con elevata disponibilità.
* La replica a livello di blocco tra sistemi storage ONTAP è rapida ed efficiente, con punti di ripristino granulari sia per il disaster recovery che per il backup.




[[cost]]
== Costo

NetApp non addebita alcun costo per l'utilizzo NetApp Replication, ma dovrai verificare con il tuo provider cloud i costi applicabili per l'ingresso e l'uscita dei dati.



[[supported-systems]]
== Sistemi supportati

NetApp Replication consente la replica dei dati tra i seguenti tipi di sistemi.

[cols="30,30"]
|===
| Sistema sorgente | Sistemi di destinazione supportati 


| Cloud Volumes ONTAP  a| 
* Amazon FSx per ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP on-premises




| cluster ONTAP on-premises  a| 
* Amazon FSx per ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP on-premises




| Amazon FSx per ONTAP  a| 
* Amazon FSx per ONTAP
* Cloud Volumes ONTAP
* cluster ONTAP on-premises


|===


[[how-data-replication-works]]
== Come funziona la replicazione dei dati

NetApp Replication semplifica la replica dei dati tra volumi su sistemi ONTAP separati utilizzando le tecnologie SnapMirror e SnapVault. Per configurare la replica, devi semplicemente identificare il volume di origine e il volume di destinazione, quindi scegliere una policy di replica e una pianificazione.

Per Cloud Volumes ONTAP, NetApp Replication acquista i dischi necessari, configura le relazioni, applica la policy di replica e quindi avvia il trasferimento di base tra i volumi.


NOTE: Il trasferimento di base include una copia completa dei dati di origine.  I trasferimenti successivi contengono copie differenziali dei dati di origine.



[[supported-data-protection-configurations]]
== Configurazioni di protezione dei dati supportate

NetApp Replication supporta configurazioni di protezione dei dati semplici, fanout e a cascata:

* In una configurazione semplice, la replicazione avviene dal volume A al volume B.
* In una configurazione fanout, la replica avviene dal volume A a più destinazioni.
* In una configurazione a cascata, la replicazione avviene dal volume A al volume B e dal volume B al volume C.




[[replicate-data-using-netapp-backup-and-recovery]]
== Replicare i dati utilizzando NetApp Backup and Recovery

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^]Ti permette di replicare i dati tra volumi su sistemi ONTAP separati, creando anche backup degli stessi dati su storage a oggetti. Se vuoi gestire sia la replica dei dati che la protezione tramite backup su storage a oggetti per gli stessi dati ONTAP in un unico servizio, prendi in considerazione l'utilizzo di NetApp Backup and Recovery.

NetApp Replication supporta le seguenti funzionalità che non sono disponibili in Backup and Recovery.

* Attualmente, Backup and Recovery non supporta la replica dei dati da o verso FSx for ONTAP systems.
* Backup and Recovery non supporta la creazione di una replica singola di un volume.


Inoltre, le relazioni a cascata sono più facili da configurare in Replication. Se hai bisogno di una qualsiasi di queste funzionalità, usa NetApp Replication.
