---
sidebar: sidebar 
permalink: task-managing-replication.html 
keywords: replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, source, destination, schedule, relationship, break, resync, max transfer, maximum transfer rate, rate, transfer rate, reverse resync, status, replication status, disaster recovery, DR, archive, archiving, retention 
summary: Dopo aver impostato la replica dei dati tra due sistemi, è possibile gestire la pianificazione e la relazione della replica dei dati da NetApp Replication. 
---
= Gestisci la replica dei dati in NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver impostato la replica dei dati tra due sistemi, è possibile gestire la pianificazione e la relazione della replica dei dati da NetApp Replication.

.Passi
. link:task-login-replication.html["Accedi a NetApp Replication"] .
. Esaminare lo stato delle relazioni di replicazione dei dati per verificare che siano integre.
+

NOTE: Se lo stato di una relazione è inattivo e lo stato mirror non è inizializzato, è necessario inizializzare la relazione dal sistema di destinazione affinché la replica dei dati avvenga secondo la pianificazione definita.  È possibile inizializzare la relazione utilizzando System Manager o l'interfaccia della riga di comando (CLI).  Questi stati possono verificarsi quando il sistema di destinazione si guasta e poi torna online.

. Selezionare il menu delle azioni per una relazione di volume e scegliere una delle azioni disponibili.
+
La tabella seguente descrive le azioni disponibili:

+
[cols="15,85"]
|===
| Azione | Descrizione 


| Informazioni | Mostra i dettagli sulla relazione del volume: informazioni sul trasferimento, informazioni sull'ultimo trasferimento, dettagli sul volume e informazioni sulla policy di protezione assegnata alla relazione. 


| Rottura | Interrompe la relazione tra i volumi di origine e di destinazione e attiva il volume di destinazione per l'accesso ai dati. Questa opzione viene in genere utilizzata quando il volume di origine non può gestire i dati a causa di eventi quali danneggiamento dei dati, eliminazione accidentale o stato offline.https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Scopri come configurare un volume di destinazione per l'accesso ai dati e riattivare un volume di origine nella documentazione ONTAP"^] 


| Risincronizzazione  a| 
Ristabilisce una relazione interrotta tra volumi e riprende la replica dei dati in base alla pianificazione definita.


NOTE: Quando si risincronizza i volumi, il contenuto del volume di destinazione viene sovrascritto dal contenuto del volume di origine.

Scopri come eseguire una risincronizzazione inversa, che risincronizza i dati dal volume di destinazione al volume di origine, vai a https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Documentazione ONTAP"^] .



| Risincronizzazione inversa | Inverte i ruoli dei volumi di origine e di destinazione. Il contenuto del volume di origine viene sovrascritto dal contenuto del volume di destinazione. Questa funzione è utile quando si desidera riattivare un volume sorgente che è andato offline. Tutti i dati scritti sul volume di origine originale tra l'ultima replica dei dati e il momento in cui il volume di origine è stato disabilitato non vengono conservati. 


| Modifica programma | Consente di scegliere una pianificazione diversa per la replica dei dati. 


| Modifica velocità di trasferimento massima | Consente di modificare la velocità massima (in kilobyte al secondo) alla quale i dati possono essere trasferiti. 


| Aggiornamento | Avvia un trasferimento incrementale per aggiornare il volume di destinazione. 


| Eliminare | Elimina la relazione di protezione dei dati tra i volumi di origine e di destinazione, il che significa che la replica dei dati non avviene più tra i volumi. Questa azione non attiva il volume di destinazione per l'accesso ai dati. 
|===


.Risultato
Dopo aver selezionato un'azione, NetApp Replication aggiorna la relazione o la pianificazione.
